import type {Metadata} from 'next';
import React from 'react';
import {Inter} from 'next/font/google';
import './globals.css';
import {AppRouterCacheProvider} from '@mui/material-nextjs/v13-appRouter';
import {StyledEngineProvider} from '@mui/material';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout ({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <StyledEngineProvider injectFirst>
      <html lang="en">
        <body className={inter.className}>
          <AppRouterCacheProvider options={{enableCssLayer: true}}>
            {children}
          </AppRouterCacheProvider>
        </body>
      </html>
    </StyledEngineProvider>
  );
}
