import type {Metadata} from 'next';
import React from 'react';
import {Fira_Code} from 'next/font/google';
import './globals.css';
import {AppRouterCacheProvider} from '@mui/material-nextjs/v13-appRouter';
import {StyledEngineProvider} from '@mui/material';
import {ThemeProvider} from '@mui/material/styles';
import theme from '@/theme';

const firaCode = Fira_Code({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout ({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <StyledEngineProvider injectFirst>
      <html lang="en">
        <body className={firaCode.className}>
          <AppRouterCacheProvider options={{enableCssLayer: true}}>
            <ThemeProvider theme={theme}>
              {children}
            </ThemeProvider>
          </AppRouterCacheProvider>
        </body>
      </html>
    </StyledEngineProvider>
  );
}
